import { z } from 'zod';
export declare const AuditEntityTypeEnum: z.ZodEnum<["passenger", "crew", "vessel", "manifest", "certification", "document", "sailing", "inspection", "user", "system"]>;
export type AuditEntityType = z.infer<typeof AuditEntityTypeEnum>;
export declare const AuditActionEnum: z.ZodEnum<["create", "read", "update", "delete", "export", "approve", "reject", "submit", "login", "logout", "failed_login", "permission_change"]>;
export type AuditAction = z.infer<typeof AuditActionEnum>;
export declare const AuditLogEntrySchema: z.ZodObject<{
    id: z.ZodString;
    entityType: z.ZodEnum<["passenger", "crew", "vessel", "manifest", "certification", "document", "sailing", "inspection", "user", "system"]>;
    entityId: z.ZodString;
    entityName: z.ZodOptional<z.ZodString>;
    action: z.ZodEnum<["create", "read", "update", "delete", "export", "approve", "reject", "submit", "login", "logout", "failed_login", "permission_change"]>;
    actionDescription: z.ZodOptional<z.ZodString>;
    userId: z.ZodString;
    userName: z.ZodString;
    userRole: z.ZodString;
    timestamp: z.ZodString;
    ipAddress: z.ZodOptional<z.ZodString>;
    userAgent: z.ZodOptional<z.ZodString>;
    sessionId: z.ZodOptional<z.ZodString>;
    previousValue: z.ZodOptional<z.ZodAny>;
    newValue: z.ZodOptional<z.ZodAny>;
    changedFields: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    reason: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    entityType: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document";
    entityId: string;
    action: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change";
    userName: string;
    userRole: string;
    timestamp: string;
    userId: string;
    entityName?: string | undefined;
    actionDescription?: string | undefined;
    ipAddress?: string | undefined;
    userAgent?: string | undefined;
    sessionId?: string | undefined;
    metadata?: Record<string, any> | undefined;
    previousValue?: any;
    newValue?: any;
    changedFields?: string[] | undefined;
    reason?: string | undefined;
}, {
    id: string;
    entityType: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document";
    entityId: string;
    action: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change";
    userName: string;
    userRole: string;
    timestamp: string;
    userId: string;
    entityName?: string | undefined;
    actionDescription?: string | undefined;
    ipAddress?: string | undefined;
    userAgent?: string | undefined;
    sessionId?: string | undefined;
    metadata?: Record<string, any> | undefined;
    previousValue?: any;
    newValue?: any;
    changedFields?: string[] | undefined;
    reason?: string | undefined;
}>;
export type AuditLogEntry = z.infer<typeof AuditLogEntrySchema>;
export declare const AuditLogFiltersSchema: z.ZodObject<{
    entityType: z.ZodOptional<z.ZodEnum<["passenger", "crew", "vessel", "manifest", "certification", "document", "sailing", "inspection", "user", "system"]>>;
    entityId: z.ZodOptional<z.ZodString>;
    action: z.ZodOptional<z.ZodEnum<["create", "read", "update", "delete", "export", "approve", "reject", "submit", "login", "logout", "failed_login", "permission_change"]>>;
    userId: z.ZodOptional<z.ZodString>;
    dateFrom: z.ZodOptional<z.ZodString>;
    dateTo: z.ZodOptional<z.ZodString>;
    page: z.ZodDefault<z.ZodNumber>;
    limit: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    page: number;
    limit: number;
    entityType?: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document" | undefined;
    entityId?: string | undefined;
    action?: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change" | undefined;
    userId?: string | undefined;
    dateFrom?: string | undefined;
    dateTo?: string | undefined;
}, {
    entityType?: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document" | undefined;
    entityId?: string | undefined;
    action?: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change" | undefined;
    userId?: string | undefined;
    dateFrom?: string | undefined;
    dateTo?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
}>;
export type AuditLogFilters = z.infer<typeof AuditLogFiltersSchema>;
export declare const AuditLogResponseSchema: z.ZodObject<{
    data: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        entityType: z.ZodEnum<["passenger", "crew", "vessel", "manifest", "certification", "document", "sailing", "inspection", "user", "system"]>;
        entityId: z.ZodString;
        entityName: z.ZodOptional<z.ZodString>;
        action: z.ZodEnum<["create", "read", "update", "delete", "export", "approve", "reject", "submit", "login", "logout", "failed_login", "permission_change"]>;
        actionDescription: z.ZodOptional<z.ZodString>;
        userId: z.ZodString;
        userName: z.ZodString;
        userRole: z.ZodString;
        timestamp: z.ZodString;
        ipAddress: z.ZodOptional<z.ZodString>;
        userAgent: z.ZodOptional<z.ZodString>;
        sessionId: z.ZodOptional<z.ZodString>;
        previousValue: z.ZodOptional<z.ZodAny>;
        newValue: z.ZodOptional<z.ZodAny>;
        changedFields: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        reason: z.ZodOptional<z.ZodString>;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    }, "strip", z.ZodTypeAny, {
        id: string;
        entityType: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document";
        entityId: string;
        action: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change";
        userName: string;
        userRole: string;
        timestamp: string;
        userId: string;
        entityName?: string | undefined;
        actionDescription?: string | undefined;
        ipAddress?: string | undefined;
        userAgent?: string | undefined;
        sessionId?: string | undefined;
        metadata?: Record<string, any> | undefined;
        previousValue?: any;
        newValue?: any;
        changedFields?: string[] | undefined;
        reason?: string | undefined;
    }, {
        id: string;
        entityType: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document";
        entityId: string;
        action: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change";
        userName: string;
        userRole: string;
        timestamp: string;
        userId: string;
        entityName?: string | undefined;
        actionDescription?: string | undefined;
        ipAddress?: string | undefined;
        userAgent?: string | undefined;
        sessionId?: string | undefined;
        metadata?: Record<string, any> | undefined;
        previousValue?: any;
        newValue?: any;
        changedFields?: string[] | undefined;
        reason?: string | undefined;
    }>, "many">;
    total: z.ZodNumber;
    page: z.ZodNumber;
    limit: z.ZodNumber;
    totalPages: z.ZodNumber;
    filters: z.ZodOptional<z.ZodObject<{
        entityType: z.ZodOptional<z.ZodEnum<["passenger", "crew", "vessel", "manifest", "certification", "document", "sailing", "inspection", "user", "system"]>>;
        entityId: z.ZodOptional<z.ZodString>;
        action: z.ZodOptional<z.ZodEnum<["create", "read", "update", "delete", "export", "approve", "reject", "submit", "login", "logout", "failed_login", "permission_change"]>>;
        userId: z.ZodOptional<z.ZodString>;
        dateFrom: z.ZodOptional<z.ZodString>;
        dateTo: z.ZodOptional<z.ZodString>;
        page: z.ZodDefault<z.ZodNumber>;
        limit: z.ZodDefault<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        page: number;
        limit: number;
        entityType?: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document" | undefined;
        entityId?: string | undefined;
        action?: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change" | undefined;
        userId?: string | undefined;
        dateFrom?: string | undefined;
        dateTo?: string | undefined;
    }, {
        entityType?: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document" | undefined;
        entityId?: string | undefined;
        action?: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change" | undefined;
        userId?: string | undefined;
        dateFrom?: string | undefined;
        dateTo?: string | undefined;
        page?: number | undefined;
        limit?: number | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    data: {
        id: string;
        entityType: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document";
        entityId: string;
        action: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change";
        userName: string;
        userRole: string;
        timestamp: string;
        userId: string;
        entityName?: string | undefined;
        actionDescription?: string | undefined;
        ipAddress?: string | undefined;
        userAgent?: string | undefined;
        sessionId?: string | undefined;
        metadata?: Record<string, any> | undefined;
        previousValue?: any;
        newValue?: any;
        changedFields?: string[] | undefined;
        reason?: string | undefined;
    }[];
    page: number;
    limit: number;
    total: number;
    totalPages: number;
    filters?: {
        page: number;
        limit: number;
        entityType?: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document" | undefined;
        entityId?: string | undefined;
        action?: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change" | undefined;
        userId?: string | undefined;
        dateFrom?: string | undefined;
        dateTo?: string | undefined;
    } | undefined;
}, {
    data: {
        id: string;
        entityType: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document";
        entityId: string;
        action: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change";
        userName: string;
        userRole: string;
        timestamp: string;
        userId: string;
        entityName?: string | undefined;
        actionDescription?: string | undefined;
        ipAddress?: string | undefined;
        userAgent?: string | undefined;
        sessionId?: string | undefined;
        metadata?: Record<string, any> | undefined;
        previousValue?: any;
        newValue?: any;
        changedFields?: string[] | undefined;
        reason?: string | undefined;
    }[];
    page: number;
    limit: number;
    total: number;
    totalPages: number;
    filters?: {
        entityType?: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document" | undefined;
        entityId?: string | undefined;
        action?: "update" | "create" | "delete" | "export" | "approve" | "read" | "reject" | "submit" | "login" | "logout" | "failed_login" | "permission_change" | undefined;
        userId?: string | undefined;
        dateFrom?: string | undefined;
        dateTo?: string | undefined;
        page?: number | undefined;
        limit?: number | undefined;
    } | undefined;
}>;
export type AuditLogResponse = z.infer<typeof AuditLogResponseSchema>;
export declare const ExportHistoryEntrySchema: z.ZodObject<{
    id: z.ZodString;
    exportType: z.ZodEnum<["passenger_manifest", "crew_list", "certification_report", "vessel_documents", "compliance_report", "audit_log"]>;
    format: z.ZodEnum<["csv", "xlsx", "pdf", "xml"]>;
    entityType: z.ZodEnum<["passenger", "crew", "vessel", "manifest", "certification", "document", "sailing", "inspection", "user", "system"]>;
    entityIds: z.ZodArray<z.ZodString, "many">;
    recordCount: z.ZodNumber;
    jurisdiction: z.ZodOptional<z.ZodString>;
    purpose: z.ZodOptional<z.ZodString>;
    exportedBy: z.ZodString;
    exportedByName: z.ZodString;
    exportedAt: z.ZodString;
    fileName: z.ZodString;
    fileSize: z.ZodNumber;
    checksum: z.ZodString;
    retainUntil: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    entityType: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document";
    exportType: "passenger_manifest" | "crew_list" | "certification_report" | "vessel_documents" | "compliance_report" | "audit_log";
    format: "csv" | "xlsx" | "pdf" | "xml";
    entityIds: string[];
    recordCount: number;
    exportedBy: string;
    exportedByName: string;
    exportedAt: string;
    fileName: string;
    fileSize: number;
    checksum: string;
    retainUntil: string;
    jurisdiction?: string | undefined;
    purpose?: string | undefined;
}, {
    id: string;
    entityType: "user" | "certification" | "vessel" | "inspection" | "sailing" | "passenger" | "system" | "crew" | "manifest" | "document";
    exportType: "passenger_manifest" | "crew_list" | "certification_report" | "vessel_documents" | "compliance_report" | "audit_log";
    format: "csv" | "xlsx" | "pdf" | "xml";
    entityIds: string[];
    recordCount: number;
    exportedBy: string;
    exportedByName: string;
    exportedAt: string;
    fileName: string;
    fileSize: number;
    checksum: string;
    retainUntil: string;
    jurisdiction?: string | undefined;
    purpose?: string | undefined;
}>;
export type ExportHistoryEntry = z.infer<typeof ExportHistoryEntrySchema>;
