import { z } from 'zod';
export declare const USCbpCrewMemberDtoSchema: z.ZodObject<{
    role: z.ZodEnum<["MASTER", "CHIEF_OFFICER", "SECOND_OFFICER", "THIRD_OFFICER", "DECK_OFFICER", "CHIEF_ENGINEER", "SECOND_ENGINEER", "THIRD_ENGINEER", "ENGINE_OFFICER", "ELECTRO_TECHNICAL_OFFICER", "ABLE_SEAMAN", "ORDINARY_SEAMAN", "RATING", "CADET", "CHIEF_STEWARD", "STEWARD", "COOK", "CHIEF_COOK", "PURSER", "SAFETY_OFFICER", "SHIP_SECURITY_OFFICER", "SECURITY_OFFICER", "RADIO_OPERATOR", "CROWD_CONTROL", "OTHER"]>;
    vesselId: z.ZodNullable<z.ZodString>;
    vesselName: z.ZodNullable<z.ZodString>;
    medicalCertificate: z.ZodNullable<z.ZodObject<{
        type: z.ZodEnum<["ENG_1", "PEME", "ILO_MLC", "OTHER"]>;
        issuingAuthority: z.ZodString;
        issueDate: z.ZodString;
        expiryDate: z.ZodString;
        documentUrl: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    }, {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    }>>;
    complianceStatus: z.ZodEnum<["compliant", "expiring", "expired", "incomplete"]>;
    expiringCertificationsCount: z.ZodNumber;
    status: z.ZodEnum<["active", "inactive", "on_leave"]>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
    familyName: z.ZodString;
    givenNames: z.ZodString;
    dateOfBirth: z.ZodString;
    placeOfBirth: z.ZodOptional<z.ZodString>;
    nationality: z.ZodString;
    gender: z.ZodEnum<["M", "F", "X"]>;
    photographUrl: z.ZodOptional<z.ZodString>;
    passportNumber: z.ZodString;
    passportIssuingCountry: z.ZodString;
    passportExpiryDate: z.ZodString;
    seamanBookNumber: z.ZodOptional<z.ZodString>;
    seamanBookIssuingAuthority: z.ZodOptional<z.ZodString>;
    id: z.ZodString;
} & {
    alienRegistrationNumber: z.ZodOptional<z.ZodString>;
    usVisaNumber: z.ZodOptional<z.ZodString>;
    usVisaType: z.ZodOptional<z.ZodEnum<["B1", "B2", "B1/B2", "D", "C1/D"]>>;
    usVisaExpiry: z.ZodOptional<z.ZodDate>;
    pscStatus: z.ZodOptional<z.ZodEnum<["CLEAR", "NOTED", "DETAINED"]>>;
    passportCountry: z.ZodString;
    passportExpiry: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    medicalCertificate: {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    } | null;
    familyName: string;
    id: string;
    role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
    createdAt: string;
    updatedAt: string;
    passportNumber: string;
    dateOfBirth: string;
    status: "active" | "inactive" | "on_leave";
    givenNames: string;
    nationality: string;
    gender: "M" | "F" | "X";
    passportCountry: string;
    passportExpiry: Date;
    vesselId: string | null;
    passportIssuingCountry: string;
    passportExpiryDate: string;
    vesselName: string | null;
    complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
    expiringCertificationsCount: number;
    alienRegistrationNumber?: string | undefined;
    placeOfBirth?: string | undefined;
    photographUrl?: string | undefined;
    seamanBookNumber?: string | undefined;
    usVisaType?: "B1" | "B2" | "B1/B2" | "D" | "C1/D" | undefined;
    usVisaExpiry?: Date | undefined;
    seamanBookIssuingAuthority?: string | undefined;
    usVisaNumber?: string | undefined;
    pscStatus?: "CLEAR" | "NOTED" | "DETAINED" | undefined;
}, {
    medicalCertificate: {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    } | null;
    familyName: string;
    id: string;
    role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
    createdAt: string;
    updatedAt: string;
    passportNumber: string;
    dateOfBirth: string;
    status: "active" | "inactive" | "on_leave";
    givenNames: string;
    nationality: string;
    gender: "M" | "F" | "X";
    passportCountry: string;
    passportExpiry: Date;
    vesselId: string | null;
    passportIssuingCountry: string;
    passportExpiryDate: string;
    vesselName: string | null;
    complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
    expiringCertificationsCount: number;
    alienRegistrationNumber?: string | undefined;
    placeOfBirth?: string | undefined;
    photographUrl?: string | undefined;
    seamanBookNumber?: string | undefined;
    usVisaType?: "B1" | "B2" | "B1/B2" | "D" | "C1/D" | undefined;
    usVisaExpiry?: Date | undefined;
    seamanBookIssuingAuthority?: string | undefined;
    usVisaNumber?: string | undefined;
    pscStatus?: "CLEAR" | "NOTED" | "DETAINED" | undefined;
}>;
export type USCbpCrewMemberDto = z.infer<typeof USCbpCrewMemberDtoSchema>;
export declare const CbpI418ManifestDtoSchema: z.ZodObject<{
    submissionId: z.ZodOptional<z.ZodString>;
    vessel: z.ZodObject<{
        status: z.ZodEnum<["active", "inactive", "laid_up", "sold"]>;
        complianceStatus: z.ZodObject<{
            safeManningCompliant: z.ZodBoolean;
            documentsValid: z.ZodBoolean;
            insuranceValid: z.ZodBoolean;
            certificatesValid: z.ZodBoolean;
        }, "strip", z.ZodTypeAny, {
            safeManningCompliant: boolean;
            documentsValid: boolean;
            insuranceValid: boolean;
            certificatesValid: boolean;
        }, {
            safeManningCompliant: boolean;
            documentsValid: boolean;
            insuranceValid: boolean;
            certificatesValid: boolean;
        }>;
        documentCount: z.ZodNumber;
        expiringDocumentsCount: z.ZodNumber;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        name: z.ZodString;
        imoNumber: z.ZodString;
        officialNumber: z.ZodOptional<z.ZodString>;
        callSign: z.ZodOptional<z.ZodString>;
        mmsi: z.ZodOptional<z.ZodString>;
        flagState: z.ZodDefault<z.ZodString>;
        portOfRegistry: z.ZodDefault<z.ZodString>;
        type: z.ZodEnum<["PASSENGER_FERRY", "RO_RO_PASSENGER", "HIGH_SPEED_CRAFT", "CARGO", "TANKER", "OTHER"]>;
        classificationSociety: z.ZodOptional<z.ZodString>;
        classNotation: z.ZodOptional<z.ZodString>;
        grossTonnage: z.ZodNumber;
        netTonnage: z.ZodNumber;
        lengthOverall: z.ZodNumber;
        breadth: z.ZodOptional<z.ZodNumber>;
        depth: z.ZodOptional<z.ZodNumber>;
        passengerCapacity: z.ZodOptional<z.ZodNumber>;
        crewCapacity: z.ZodOptional<z.ZodNumber>;
        vehicleCapacity: z.ZodOptional<z.ZodNumber>;
        engineType: z.ZodOptional<z.ZodString>;
        engineCount: z.ZodOptional<z.ZodNumber>;
        propulsionPower: z.ZodOptional<z.ZodNumber>;
        registeredOwner: z.ZodObject<{
            name: z.ZodString;
            type: z.ZodEnum<["individual", "company"]>;
            address: z.ZodObject<{
                street: z.ZodString;
                city: z.ZodString;
                state: z.ZodOptional<z.ZodString>;
                postalCode: z.ZodOptional<z.ZodString>;
                country: z.ZodString;
            }, "strip", z.ZodTypeAny, {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            }, {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            }>;
            contactEmail: z.ZodString;
            contactPhone: z.ZodString;
            registrationNumber: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        }, {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        }>;
        managingOwner: z.ZodOptional<z.ZodObject<{
            name: z.ZodString;
            type: z.ZodEnum<["individual", "company"]>;
            address: z.ZodObject<{
                street: z.ZodString;
                city: z.ZodString;
                state: z.ZodOptional<z.ZodString>;
                postalCode: z.ZodOptional<z.ZodString>;
                country: z.ZodString;
            }, "strip", z.ZodTypeAny, {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            }, {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            }>;
            contactEmail: z.ZodString;
            contactPhone: z.ZodString;
            registrationNumber: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        }, {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        }>>;
        yearBuilt: z.ZodNumber;
        builder: z.ZodOptional<z.ZodString>;
        buildCountry: z.ZodOptional<z.ZodString>;
        id: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        type: "PASSENGER_FERRY" | "RO_RO_PASSENGER" | "HIGH_SPEED_CRAFT" | "CARGO" | "TANKER" | "OTHER";
        name: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        imoNumber: string;
        flagState: string;
        portOfRegistry: string;
        grossTonnage: number;
        netTonnage: number;
        lengthOverall: number;
        yearBuilt: number;
        status: "active" | "inactive" | "laid_up" | "sold";
        complianceStatus: {
            safeManningCompliant: boolean;
            documentsValid: boolean;
            insuranceValid: boolean;
            certificatesValid: boolean;
        };
        registeredOwner: {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        };
        documentCount: number;
        expiringDocumentsCount: number;
        officialNumber?: string | undefined;
        callSign?: string | undefined;
        mmsi?: string | undefined;
        classificationSociety?: string | undefined;
        classNotation?: string | undefined;
        breadth?: number | undefined;
        depth?: number | undefined;
        passengerCapacity?: number | undefined;
        crewCapacity?: number | undefined;
        vehicleCapacity?: number | undefined;
        engineType?: string | undefined;
        engineCount?: number | undefined;
        propulsionPower?: number | undefined;
        builder?: string | undefined;
        buildCountry?: string | undefined;
        managingOwner?: {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        } | undefined;
    }, {
        type: "PASSENGER_FERRY" | "RO_RO_PASSENGER" | "HIGH_SPEED_CRAFT" | "CARGO" | "TANKER" | "OTHER";
        name: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        imoNumber: string;
        grossTonnage: number;
        netTonnage: number;
        lengthOverall: number;
        yearBuilt: number;
        status: "active" | "inactive" | "laid_up" | "sold";
        complianceStatus: {
            safeManningCompliant: boolean;
            documentsValid: boolean;
            insuranceValid: boolean;
            certificatesValid: boolean;
        };
        registeredOwner: {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        };
        documentCount: number;
        expiringDocumentsCount: number;
        officialNumber?: string | undefined;
        callSign?: string | undefined;
        mmsi?: string | undefined;
        flagState?: string | undefined;
        portOfRegistry?: string | undefined;
        classificationSociety?: string | undefined;
        classNotation?: string | undefined;
        breadth?: number | undefined;
        depth?: number | undefined;
        passengerCapacity?: number | undefined;
        crewCapacity?: number | undefined;
        vehicleCapacity?: number | undefined;
        engineType?: string | undefined;
        engineCount?: number | undefined;
        propulsionPower?: number | undefined;
        builder?: string | undefined;
        buildCountry?: string | undefined;
        managingOwner?: {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        } | undefined;
    }>;
    crewMembers: z.ZodArray<z.ZodObject<{
        role: z.ZodEnum<["MASTER", "CHIEF_OFFICER", "SECOND_OFFICER", "THIRD_OFFICER", "DECK_OFFICER", "CHIEF_ENGINEER", "SECOND_ENGINEER", "THIRD_ENGINEER", "ENGINE_OFFICER", "ELECTRO_TECHNICAL_OFFICER", "ABLE_SEAMAN", "ORDINARY_SEAMAN", "RATING", "CADET", "CHIEF_STEWARD", "STEWARD", "COOK", "CHIEF_COOK", "PURSER", "SAFETY_OFFICER", "SHIP_SECURITY_OFFICER", "SECURITY_OFFICER", "RADIO_OPERATOR", "CROWD_CONTROL", "OTHER"]>;
        vesselId: z.ZodNullable<z.ZodString>;
        vesselName: z.ZodNullable<z.ZodString>;
        medicalCertificate: z.ZodNullable<z.ZodObject<{
            type: z.ZodEnum<["ENG_1", "PEME", "ILO_MLC", "OTHER"]>;
            issuingAuthority: z.ZodString;
            issueDate: z.ZodString;
            expiryDate: z.ZodString;
            documentUrl: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        }, {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        }>>;
        complianceStatus: z.ZodEnum<["compliant", "expiring", "expired", "incomplete"]>;
        expiringCertificationsCount: z.ZodNumber;
        status: z.ZodEnum<["active", "inactive", "on_leave"]>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        familyName: z.ZodString;
        givenNames: z.ZodString;
        dateOfBirth: z.ZodString;
        placeOfBirth: z.ZodOptional<z.ZodString>;
        nationality: z.ZodString;
        gender: z.ZodEnum<["M", "F", "X"]>;
        photographUrl: z.ZodOptional<z.ZodString>;
        passportNumber: z.ZodString;
        passportIssuingCountry: z.ZodString;
        passportExpiryDate: z.ZodString;
        seamanBookNumber: z.ZodOptional<z.ZodString>;
        seamanBookIssuingAuthority: z.ZodOptional<z.ZodString>;
        id: z.ZodString;
    } & {
        alienRegistrationNumber: z.ZodOptional<z.ZodString>;
        usVisaNumber: z.ZodOptional<z.ZodString>;
        usVisaType: z.ZodOptional<z.ZodEnum<["B1", "B2", "B1/B2", "D", "C1/D"]>>;
        usVisaExpiry: z.ZodOptional<z.ZodDate>;
        pscStatus: z.ZodOptional<z.ZodEnum<["CLEAR", "NOTED", "DETAINED"]>>;
        passportCountry: z.ZodString;
        passportExpiry: z.ZodDate;
    }, "strip", z.ZodTypeAny, {
        medicalCertificate: {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        } | null;
        familyName: string;
        id: string;
        role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
        createdAt: string;
        updatedAt: string;
        passportNumber: string;
        dateOfBirth: string;
        status: "active" | "inactive" | "on_leave";
        givenNames: string;
        nationality: string;
        gender: "M" | "F" | "X";
        passportCountry: string;
        passportExpiry: Date;
        vesselId: string | null;
        passportIssuingCountry: string;
        passportExpiryDate: string;
        vesselName: string | null;
        complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
        expiringCertificationsCount: number;
        alienRegistrationNumber?: string | undefined;
        placeOfBirth?: string | undefined;
        photographUrl?: string | undefined;
        seamanBookNumber?: string | undefined;
        usVisaType?: "B1" | "B2" | "B1/B2" | "D" | "C1/D" | undefined;
        usVisaExpiry?: Date | undefined;
        seamanBookIssuingAuthority?: string | undefined;
        usVisaNumber?: string | undefined;
        pscStatus?: "CLEAR" | "NOTED" | "DETAINED" | undefined;
    }, {
        medicalCertificate: {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        } | null;
        familyName: string;
        id: string;
        role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
        createdAt: string;
        updatedAt: string;
        passportNumber: string;
        dateOfBirth: string;
        status: "active" | "inactive" | "on_leave";
        givenNames: string;
        nationality: string;
        gender: "M" | "F" | "X";
        passportCountry: string;
        passportExpiry: Date;
        vesselId: string | null;
        passportIssuingCountry: string;
        passportExpiryDate: string;
        vesselName: string | null;
        complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
        expiringCertificationsCount: number;
        alienRegistrationNumber?: string | undefined;
        placeOfBirth?: string | undefined;
        photographUrl?: string | undefined;
        seamanBookNumber?: string | undefined;
        usVisaType?: "B1" | "B2" | "B1/B2" | "D" | "C1/D" | undefined;
        usVisaExpiry?: Date | undefined;
        seamanBookIssuingAuthority?: string | undefined;
        usVisaNumber?: string | undefined;
        pscStatus?: "CLEAR" | "NOTED" | "DETAINED" | undefined;
    }>, "many">;
    arrivalPort: z.ZodEnum<["2704"]>;
    departurePort: z.ZodString;
    eta: z.ZodDate;
    etd: z.ZodDate;
    voyageNumber: z.ZodString;
    status: z.ZodEnum<["DRAFT", "SUBMITTED", "ACCEPTED", "REJECTED"]>;
    submittedAt: z.ZodOptional<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    vessel: {
        type: "PASSENGER_FERRY" | "RO_RO_PASSENGER" | "HIGH_SPEED_CRAFT" | "CARGO" | "TANKER" | "OTHER";
        name: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        imoNumber: string;
        flagState: string;
        portOfRegistry: string;
        grossTonnage: number;
        netTonnage: number;
        lengthOverall: number;
        yearBuilt: number;
        status: "active" | "inactive" | "laid_up" | "sold";
        complianceStatus: {
            safeManningCompliant: boolean;
            documentsValid: boolean;
            insuranceValid: boolean;
            certificatesValid: boolean;
        };
        registeredOwner: {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        };
        documentCount: number;
        expiringDocumentsCount: number;
        officialNumber?: string | undefined;
        callSign?: string | undefined;
        mmsi?: string | undefined;
        classificationSociety?: string | undefined;
        classNotation?: string | undefined;
        breadth?: number | undefined;
        depth?: number | undefined;
        passengerCapacity?: number | undefined;
        crewCapacity?: number | undefined;
        vehicleCapacity?: number | undefined;
        engineType?: string | undefined;
        engineCount?: number | undefined;
        propulsionPower?: number | undefined;
        builder?: string | undefined;
        buildCountry?: string | undefined;
        managingOwner?: {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        } | undefined;
    };
    crewMembers: {
        medicalCertificate: {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        } | null;
        familyName: string;
        id: string;
        role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
        createdAt: string;
        updatedAt: string;
        passportNumber: string;
        dateOfBirth: string;
        status: "active" | "inactive" | "on_leave";
        givenNames: string;
        nationality: string;
        gender: "M" | "F" | "X";
        passportCountry: string;
        passportExpiry: Date;
        vesselId: string | null;
        passportIssuingCountry: string;
        passportExpiryDate: string;
        vesselName: string | null;
        complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
        expiringCertificationsCount: number;
        alienRegistrationNumber?: string | undefined;
        placeOfBirth?: string | undefined;
        photographUrl?: string | undefined;
        seamanBookNumber?: string | undefined;
        usVisaType?: "B1" | "B2" | "B1/B2" | "D" | "C1/D" | undefined;
        usVisaExpiry?: Date | undefined;
        seamanBookIssuingAuthority?: string | undefined;
        usVisaNumber?: string | undefined;
        pscStatus?: "CLEAR" | "NOTED" | "DETAINED" | undefined;
    }[];
    status: "ACCEPTED" | "REJECTED" | "DRAFT" | "SUBMITTED";
    eta: Date;
    etd: Date;
    voyageNumber: string;
    arrivalPort: "2704";
    departurePort: string;
    submittedAt?: Date | undefined;
    submissionId?: string | undefined;
}, {
    vessel: {
        type: "PASSENGER_FERRY" | "RO_RO_PASSENGER" | "HIGH_SPEED_CRAFT" | "CARGO" | "TANKER" | "OTHER";
        name: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        imoNumber: string;
        grossTonnage: number;
        netTonnage: number;
        lengthOverall: number;
        yearBuilt: number;
        status: "active" | "inactive" | "laid_up" | "sold";
        complianceStatus: {
            safeManningCompliant: boolean;
            documentsValid: boolean;
            insuranceValid: boolean;
            certificatesValid: boolean;
        };
        registeredOwner: {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        };
        documentCount: number;
        expiringDocumentsCount: number;
        officialNumber?: string | undefined;
        callSign?: string | undefined;
        mmsi?: string | undefined;
        flagState?: string | undefined;
        portOfRegistry?: string | undefined;
        classificationSociety?: string | undefined;
        classNotation?: string | undefined;
        breadth?: number | undefined;
        depth?: number | undefined;
        passengerCapacity?: number | undefined;
        crewCapacity?: number | undefined;
        vehicleCapacity?: number | undefined;
        engineType?: string | undefined;
        engineCount?: number | undefined;
        propulsionPower?: number | undefined;
        builder?: string | undefined;
        buildCountry?: string | undefined;
        managingOwner?: {
            type: "individual" | "company";
            name: string;
            address: {
                street: string;
                city: string;
                country: string;
                state?: string | undefined;
                postalCode?: string | undefined;
            };
            contactEmail: string;
            contactPhone: string;
            registrationNumber?: string | undefined;
        } | undefined;
    };
    crewMembers: {
        medicalCertificate: {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        } | null;
        familyName: string;
        id: string;
        role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
        createdAt: string;
        updatedAt: string;
        passportNumber: string;
        dateOfBirth: string;
        status: "active" | "inactive" | "on_leave";
        givenNames: string;
        nationality: string;
        gender: "M" | "F" | "X";
        passportCountry: string;
        passportExpiry: Date;
        vesselId: string | null;
        passportIssuingCountry: string;
        passportExpiryDate: string;
        vesselName: string | null;
        complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
        expiringCertificationsCount: number;
        alienRegistrationNumber?: string | undefined;
        placeOfBirth?: string | undefined;
        photographUrl?: string | undefined;
        seamanBookNumber?: string | undefined;
        usVisaType?: "B1" | "B2" | "B1/B2" | "D" | "C1/D" | undefined;
        usVisaExpiry?: Date | undefined;
        seamanBookIssuingAuthority?: string | undefined;
        usVisaNumber?: string | undefined;
        pscStatus?: "CLEAR" | "NOTED" | "DETAINED" | undefined;
    }[];
    status: "ACCEPTED" | "REJECTED" | "DRAFT" | "SUBMITTED";
    eta: Date;
    etd: Date;
    voyageNumber: string;
    arrivalPort: "2704";
    departurePort: string;
    submittedAt?: Date | undefined;
    submissionId?: string | undefined;
}>;
export type CbpI418ManifestDto = z.infer<typeof CbpI418ManifestDtoSchema>;
