import { z } from 'zod';
export declare const STCWCertTypeEnum: z.ZodEnum<["MASTER", "CHIEF_MATE", "OFFICER_OF_THE_WATCH_DECK", "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH", "ABLE_SEAFARER_DECK", "CHIEF_ENGINEER", "SECOND_ENGINEER", "OFFICER_OF_THE_WATCH_ENGINE", "RATING_FORMING_PART_OF_ENGINE_WATCH", "ABLE_SEAFARER_ENGINE", "ELECTRO_TECHNICAL_OFFICER", "GMDSS_GOC", "GMDSS_ROC", "TANKER_FAMILIARIZATION", "OIL_TANKER_CARGO", "CHEMICAL_TANKER_CARGO", "LIQUEFIED_GAS_TANKER_CARGO", "PASSENGER_SHIP_CROWD_MANAGEMENT", "PASSENGER_SHIP_CRISIS_MANAGEMENT", "PASSENGER_SHIP_SAFETY", "BASIC_SAFETY_TRAINING", "SURVIVAL_CRAFT", "ADVANCED_FIREFIGHTING", "MEDICAL_FIRST_AID", "MEDICAL_CARE", "SECURITY_AWARENESS", "SHIP_SECURITY_OFFICER", "ENDORSEMENT", "OTHER"]>;
export type STCWCertType = z.infer<typeof STCWCertTypeEnum>;
export declare const CertificationStatusEnum: z.ZodEnum<["valid", "expiring", "expired", "revoked", "pending_verification"]>;
export type CertificationStatus = z.infer<typeof CertificationStatusEnum>;
export declare const CreateCertificationSchema: z.ZodObject<{
    crewId: z.ZodString;
    type: z.ZodEnum<["MASTER", "CHIEF_MATE", "OFFICER_OF_THE_WATCH_DECK", "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH", "ABLE_SEAFARER_DECK", "CHIEF_ENGINEER", "SECOND_ENGINEER", "OFFICER_OF_THE_WATCH_ENGINE", "RATING_FORMING_PART_OF_ENGINE_WATCH", "ABLE_SEAFARER_ENGINE", "ELECTRO_TECHNICAL_OFFICER", "GMDSS_GOC", "GMDSS_ROC", "TANKER_FAMILIARIZATION", "OIL_TANKER_CARGO", "CHEMICAL_TANKER_CARGO", "LIQUEFIED_GAS_TANKER_CARGO", "PASSENGER_SHIP_CROWD_MANAGEMENT", "PASSENGER_SHIP_CRISIS_MANAGEMENT", "PASSENGER_SHIP_SAFETY", "BASIC_SAFETY_TRAINING", "SURVIVAL_CRAFT", "ADVANCED_FIREFIGHTING", "MEDICAL_FIRST_AID", "MEDICAL_CARE", "SECURITY_AWARENESS", "SHIP_SECURITY_OFFICER", "ENDORSEMENT", "OTHER"]>;
    certificateNumber: z.ZodString;
    issuingAuthority: z.ZodString;
    issuingCountry: z.ZodString;
    issueDate: z.ZodString;
    expiryDate: z.ZodString;
    documentUrl: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "OTHER" | "MASTER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "ELECTRO_TECHNICAL_OFFICER" | "SHIP_SECURITY_OFFICER" | "CHIEF_MATE" | "OFFICER_OF_THE_WATCH_DECK" | "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH" | "ABLE_SEAFARER_DECK" | "OFFICER_OF_THE_WATCH_ENGINE" | "RATING_FORMING_PART_OF_ENGINE_WATCH" | "ABLE_SEAFARER_ENGINE" | "GMDSS_GOC" | "GMDSS_ROC" | "TANKER_FAMILIARIZATION" | "OIL_TANKER_CARGO" | "CHEMICAL_TANKER_CARGO" | "LIQUEFIED_GAS_TANKER_CARGO" | "PASSENGER_SHIP_CROWD_MANAGEMENT" | "PASSENGER_SHIP_CRISIS_MANAGEMENT" | "PASSENGER_SHIP_SAFETY" | "BASIC_SAFETY_TRAINING" | "SURVIVAL_CRAFT" | "ADVANCED_FIREFIGHTING" | "MEDICAL_FIRST_AID" | "MEDICAL_CARE" | "SECURITY_AWARENESS" | "ENDORSEMENT";
    issuingAuthority: string;
    issueDate: string;
    expiryDate: string;
    crewId: string;
    certificateNumber: string;
    issuingCountry: string;
    documentUrl?: string | undefined;
    notes?: string | undefined;
}, {
    type: "OTHER" | "MASTER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "ELECTRO_TECHNICAL_OFFICER" | "SHIP_SECURITY_OFFICER" | "CHIEF_MATE" | "OFFICER_OF_THE_WATCH_DECK" | "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH" | "ABLE_SEAFARER_DECK" | "OFFICER_OF_THE_WATCH_ENGINE" | "RATING_FORMING_PART_OF_ENGINE_WATCH" | "ABLE_SEAFARER_ENGINE" | "GMDSS_GOC" | "GMDSS_ROC" | "TANKER_FAMILIARIZATION" | "OIL_TANKER_CARGO" | "CHEMICAL_TANKER_CARGO" | "LIQUEFIED_GAS_TANKER_CARGO" | "PASSENGER_SHIP_CROWD_MANAGEMENT" | "PASSENGER_SHIP_CRISIS_MANAGEMENT" | "PASSENGER_SHIP_SAFETY" | "BASIC_SAFETY_TRAINING" | "SURVIVAL_CRAFT" | "ADVANCED_FIREFIGHTING" | "MEDICAL_FIRST_AID" | "MEDICAL_CARE" | "SECURITY_AWARENESS" | "ENDORSEMENT";
    issuingAuthority: string;
    issueDate: string;
    expiryDate: string;
    crewId: string;
    certificateNumber: string;
    issuingCountry: string;
    documentUrl?: string | undefined;
    notes?: string | undefined;
}>;
export type CreateCertification = z.infer<typeof CreateCertificationSchema>;
export declare const CertificationSchema: z.ZodObject<{
    id: z.ZodString;
    crewId: z.ZodString;
    crewName: z.ZodString;
    type: z.ZodEnum<["MASTER", "CHIEF_MATE", "OFFICER_OF_THE_WATCH_DECK", "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH", "ABLE_SEAFARER_DECK", "CHIEF_ENGINEER", "SECOND_ENGINEER", "OFFICER_OF_THE_WATCH_ENGINE", "RATING_FORMING_PART_OF_ENGINE_WATCH", "ABLE_SEAFARER_ENGINE", "ELECTRO_TECHNICAL_OFFICER", "GMDSS_GOC", "GMDSS_ROC", "TANKER_FAMILIARIZATION", "OIL_TANKER_CARGO", "CHEMICAL_TANKER_CARGO", "LIQUEFIED_GAS_TANKER_CARGO", "PASSENGER_SHIP_CROWD_MANAGEMENT", "PASSENGER_SHIP_CRISIS_MANAGEMENT", "PASSENGER_SHIP_SAFETY", "BASIC_SAFETY_TRAINING", "SURVIVAL_CRAFT", "ADVANCED_FIREFIGHTING", "MEDICAL_FIRST_AID", "MEDICAL_CARE", "SECURITY_AWARENESS", "SHIP_SECURITY_OFFICER", "ENDORSEMENT", "OTHER"]>;
    typeName: z.ZodString;
    certificateNumber: z.ZodString;
    issuingAuthority: z.ZodString;
    issuingCountry: z.ZodString;
    issueDate: z.ZodString;
    expiryDate: z.ZodString;
    daysUntilExpiry: z.ZodNumber;
    status: z.ZodEnum<["valid", "expiring", "expired", "revoked", "pending_verification"]>;
    documentUrl: z.ZodNullable<z.ZodString>;
    documentVerified: z.ZodBoolean;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
    verifiedAt: z.ZodNullable<z.ZodString>;
    verifiedBy: z.ZodNullable<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "OTHER" | "MASTER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "ELECTRO_TECHNICAL_OFFICER" | "SHIP_SECURITY_OFFICER" | "CHIEF_MATE" | "OFFICER_OF_THE_WATCH_DECK" | "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH" | "ABLE_SEAFARER_DECK" | "OFFICER_OF_THE_WATCH_ENGINE" | "RATING_FORMING_PART_OF_ENGINE_WATCH" | "ABLE_SEAFARER_ENGINE" | "GMDSS_GOC" | "GMDSS_ROC" | "TANKER_FAMILIARIZATION" | "OIL_TANKER_CARGO" | "CHEMICAL_TANKER_CARGO" | "LIQUEFIED_GAS_TANKER_CARGO" | "PASSENGER_SHIP_CROWD_MANAGEMENT" | "PASSENGER_SHIP_CRISIS_MANAGEMENT" | "PASSENGER_SHIP_SAFETY" | "BASIC_SAFETY_TRAINING" | "SURVIVAL_CRAFT" | "ADVANCED_FIREFIGHTING" | "MEDICAL_FIRST_AID" | "MEDICAL_CARE" | "SECURITY_AWARENESS" | "ENDORSEMENT";
    id: string;
    createdAt: string;
    updatedAt: string;
    status: "valid" | "expiring" | "expired" | "revoked" | "pending_verification";
    issuingAuthority: string;
    issueDate: string;
    expiryDate: string;
    documentUrl: string | null;
    typeName: string;
    daysUntilExpiry: number;
    verifiedAt: string | null;
    verifiedBy: string | null;
    crewId: string;
    certificateNumber: string;
    issuingCountry: string;
    crewName: string;
    documentVerified: boolean;
}, {
    type: "OTHER" | "MASTER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "ELECTRO_TECHNICAL_OFFICER" | "SHIP_SECURITY_OFFICER" | "CHIEF_MATE" | "OFFICER_OF_THE_WATCH_DECK" | "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH" | "ABLE_SEAFARER_DECK" | "OFFICER_OF_THE_WATCH_ENGINE" | "RATING_FORMING_PART_OF_ENGINE_WATCH" | "ABLE_SEAFARER_ENGINE" | "GMDSS_GOC" | "GMDSS_ROC" | "TANKER_FAMILIARIZATION" | "OIL_TANKER_CARGO" | "CHEMICAL_TANKER_CARGO" | "LIQUEFIED_GAS_TANKER_CARGO" | "PASSENGER_SHIP_CROWD_MANAGEMENT" | "PASSENGER_SHIP_CRISIS_MANAGEMENT" | "PASSENGER_SHIP_SAFETY" | "BASIC_SAFETY_TRAINING" | "SURVIVAL_CRAFT" | "ADVANCED_FIREFIGHTING" | "MEDICAL_FIRST_AID" | "MEDICAL_CARE" | "SECURITY_AWARENESS" | "ENDORSEMENT";
    id: string;
    createdAt: string;
    updatedAt: string;
    status: "valid" | "expiring" | "expired" | "revoked" | "pending_verification";
    issuingAuthority: string;
    issueDate: string;
    expiryDate: string;
    documentUrl: string | null;
    typeName: string;
    daysUntilExpiry: number;
    verifiedAt: string | null;
    verifiedBy: string | null;
    crewId: string;
    certificateNumber: string;
    issuingCountry: string;
    crewName: string;
    documentVerified: boolean;
}>;
export type Certification = z.infer<typeof CertificationSchema>;
export declare const CertificationFiltersSchema: z.ZodObject<{
    crewId: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<["MASTER", "CHIEF_MATE", "OFFICER_OF_THE_WATCH_DECK", "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH", "ABLE_SEAFARER_DECK", "CHIEF_ENGINEER", "SECOND_ENGINEER", "OFFICER_OF_THE_WATCH_ENGINE", "RATING_FORMING_PART_OF_ENGINE_WATCH", "ABLE_SEAFARER_ENGINE", "ELECTRO_TECHNICAL_OFFICER", "GMDSS_GOC", "GMDSS_ROC", "TANKER_FAMILIARIZATION", "OIL_TANKER_CARGO", "CHEMICAL_TANKER_CARGO", "LIQUEFIED_GAS_TANKER_CARGO", "PASSENGER_SHIP_CROWD_MANAGEMENT", "PASSENGER_SHIP_CRISIS_MANAGEMENT", "PASSENGER_SHIP_SAFETY", "BASIC_SAFETY_TRAINING", "SURVIVAL_CRAFT", "ADVANCED_FIREFIGHTING", "MEDICAL_FIRST_AID", "MEDICAL_CARE", "SECURITY_AWARENESS", "SHIP_SECURITY_OFFICER", "ENDORSEMENT", "OTHER"]>>;
    status: z.ZodOptional<z.ZodEnum<["valid", "expiring", "expired", "revoked", "pending_verification"]>>;
    expiringWithinDays: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    type?: "OTHER" | "MASTER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "ELECTRO_TECHNICAL_OFFICER" | "SHIP_SECURITY_OFFICER" | "CHIEF_MATE" | "OFFICER_OF_THE_WATCH_DECK" | "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH" | "ABLE_SEAFARER_DECK" | "OFFICER_OF_THE_WATCH_ENGINE" | "RATING_FORMING_PART_OF_ENGINE_WATCH" | "ABLE_SEAFARER_ENGINE" | "GMDSS_GOC" | "GMDSS_ROC" | "TANKER_FAMILIARIZATION" | "OIL_TANKER_CARGO" | "CHEMICAL_TANKER_CARGO" | "LIQUEFIED_GAS_TANKER_CARGO" | "PASSENGER_SHIP_CROWD_MANAGEMENT" | "PASSENGER_SHIP_CRISIS_MANAGEMENT" | "PASSENGER_SHIP_SAFETY" | "BASIC_SAFETY_TRAINING" | "SURVIVAL_CRAFT" | "ADVANCED_FIREFIGHTING" | "MEDICAL_FIRST_AID" | "MEDICAL_CARE" | "SECURITY_AWARENESS" | "ENDORSEMENT" | undefined;
    status?: "valid" | "expiring" | "expired" | "revoked" | "pending_verification" | undefined;
    crewId?: string | undefined;
    expiringWithinDays?: number | undefined;
}, {
    type?: "OTHER" | "MASTER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "ELECTRO_TECHNICAL_OFFICER" | "SHIP_SECURITY_OFFICER" | "CHIEF_MATE" | "OFFICER_OF_THE_WATCH_DECK" | "RATING_FORMING_PART_OF_NAVIGATIONAL_WATCH" | "ABLE_SEAFARER_DECK" | "OFFICER_OF_THE_WATCH_ENGINE" | "RATING_FORMING_PART_OF_ENGINE_WATCH" | "ABLE_SEAFARER_ENGINE" | "GMDSS_GOC" | "GMDSS_ROC" | "TANKER_FAMILIARIZATION" | "OIL_TANKER_CARGO" | "CHEMICAL_TANKER_CARGO" | "LIQUEFIED_GAS_TANKER_CARGO" | "PASSENGER_SHIP_CROWD_MANAGEMENT" | "PASSENGER_SHIP_CRISIS_MANAGEMENT" | "PASSENGER_SHIP_SAFETY" | "BASIC_SAFETY_TRAINING" | "SURVIVAL_CRAFT" | "ADVANCED_FIREFIGHTING" | "MEDICAL_FIRST_AID" | "MEDICAL_CARE" | "SECURITY_AWARENESS" | "ENDORSEMENT" | undefined;
    status?: "valid" | "expiring" | "expired" | "revoked" | "pending_verification" | undefined;
    crewId?: string | undefined;
    expiringWithinDays?: number | undefined;
}>;
export type CertificationFilters = z.infer<typeof CertificationFiltersSchema>;
export declare const ROLE_CERTIFICATION_REQUIREMENTS: Record<string, STCWCertType[]>;
export declare const validateCrewCertifications: (role: string, certifications: Certification[], sailingDate: Date) => {
    valid: boolean;
    missing: string[];
    expired: string[];
};
