import { z } from 'zod';
export declare const CrewRoleEnum: z.ZodEnum<["MASTER", "CHIEF_OFFICER", "SECOND_OFFICER", "THIRD_OFFICER", "DECK_OFFICER", "CHIEF_ENGINEER", "SECOND_ENGINEER", "THIRD_ENGINEER", "ENGINE_OFFICER", "ELECTRO_TECHNICAL_OFFICER", "ABLE_SEAMAN", "ORDINARY_SEAMAN", "RATING", "CADET", "CHIEF_STEWARD", "STEWARD", "COOK", "CHIEF_COOK", "PURSER", "SAFETY_OFFICER", "SHIP_SECURITY_OFFICER", "SECURITY_OFFICER", "RADIO_OPERATOR", "CROWD_CONTROL", "OTHER"]>;
export type CrewRole = z.infer<typeof CrewRoleEnum>;
export declare const CrewIdentitySchema: z.ZodObject<{
    familyName: z.ZodString;
    givenNames: z.ZodString;
    dateOfBirth: z.ZodString;
    placeOfBirth: z.ZodOptional<z.ZodString>;
    nationality: z.ZodString;
    gender: z.ZodEnum<["M", "F", "X"]>;
    photographUrl: z.ZodOptional<z.ZodString>;
    passportNumber: z.ZodString;
    passportIssuingCountry: z.ZodString;
    passportExpiryDate: z.ZodString;
    seamanBookNumber: z.ZodOptional<z.ZodString>;
    seamanBookIssuingAuthority: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    familyName: string;
    passportNumber: string;
    dateOfBirth: string;
    givenNames: string;
    nationality: string;
    gender: "M" | "F" | "X";
    passportIssuingCountry: string;
    passportExpiryDate: string;
    placeOfBirth?: string | undefined;
    photographUrl?: string | undefined;
    seamanBookNumber?: string | undefined;
    seamanBookIssuingAuthority?: string | undefined;
}, {
    familyName: string;
    passportNumber: string;
    dateOfBirth: string;
    givenNames: string;
    nationality: string;
    gender: "M" | "F" | "X";
    passportIssuingCountry: string;
    passportExpiryDate: string;
    placeOfBirth?: string | undefined;
    photographUrl?: string | undefined;
    seamanBookNumber?: string | undefined;
    seamanBookIssuingAuthority?: string | undefined;
}>;
export type CrewIdentity = z.infer<typeof CrewIdentitySchema>;
export declare const MedicalCertificateSchema: z.ZodObject<{
    type: z.ZodEnum<["ENG_1", "PEME", "ILO_MLC", "OTHER"]>;
    issuingAuthority: z.ZodString;
    issueDate: z.ZodString;
    expiryDate: z.ZodString;
    documentUrl: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
    issuingAuthority: string;
    issueDate: string;
    expiryDate: string;
    documentUrl?: string | undefined;
}, {
    type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
    issuingAuthority: string;
    issueDate: string;
    expiryDate: string;
    documentUrl?: string | undefined;
}>;
export type MedicalCertificate = z.infer<typeof MedicalCertificateSchema>;
export declare const CreateCrewMemberSchema: z.ZodObject<{
    role: z.ZodEnum<["MASTER", "CHIEF_OFFICER", "SECOND_OFFICER", "THIRD_OFFICER", "DECK_OFFICER", "CHIEF_ENGINEER", "SECOND_ENGINEER", "THIRD_ENGINEER", "ENGINE_OFFICER", "ELECTRO_TECHNICAL_OFFICER", "ABLE_SEAMAN", "ORDINARY_SEAMAN", "RATING", "CADET", "CHIEF_STEWARD", "STEWARD", "COOK", "CHIEF_COOK", "PURSER", "SAFETY_OFFICER", "SHIP_SECURITY_OFFICER", "SECURITY_OFFICER", "RADIO_OPERATOR", "CROWD_CONTROL", "OTHER"]>;
    vesselId: z.ZodOptional<z.ZodString>;
    medicalCertificate: z.ZodOptional<z.ZodObject<{
        type: z.ZodEnum<["ENG_1", "PEME", "ILO_MLC", "OTHER"]>;
        issuingAuthority: z.ZodString;
        issueDate: z.ZodString;
        expiryDate: z.ZodString;
        documentUrl: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    }, {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    }>>;
    employmentStartDate: z.ZodOptional<z.ZodString>;
    contractType: z.ZodOptional<z.ZodEnum<["permanent", "contract", "temporary"]>>;
    familyName: z.ZodString;
    givenNames: z.ZodString;
    dateOfBirth: z.ZodString;
    placeOfBirth: z.ZodOptional<z.ZodString>;
    nationality: z.ZodString;
    gender: z.ZodEnum<["M", "F", "X"]>;
    photographUrl: z.ZodOptional<z.ZodString>;
    passportNumber: z.ZodString;
    passportIssuingCountry: z.ZodString;
    passportExpiryDate: z.ZodString;
    seamanBookNumber: z.ZodOptional<z.ZodString>;
    seamanBookIssuingAuthority: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    familyName: string;
    role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
    passportNumber: string;
    dateOfBirth: string;
    givenNames: string;
    nationality: string;
    gender: "M" | "F" | "X";
    passportIssuingCountry: string;
    passportExpiryDate: string;
    medicalCertificate?: {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    } | undefined;
    placeOfBirth?: string | undefined;
    photographUrl?: string | undefined;
    seamanBookNumber?: string | undefined;
    vesselId?: string | undefined;
    employmentStartDate?: string | undefined;
    contractType?: "permanent" | "contract" | "temporary" | undefined;
    seamanBookIssuingAuthority?: string | undefined;
}, {
    familyName: string;
    role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
    passportNumber: string;
    dateOfBirth: string;
    givenNames: string;
    nationality: string;
    gender: "M" | "F" | "X";
    passportIssuingCountry: string;
    passportExpiryDate: string;
    medicalCertificate?: {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    } | undefined;
    placeOfBirth?: string | undefined;
    photographUrl?: string | undefined;
    seamanBookNumber?: string | undefined;
    vesselId?: string | undefined;
    employmentStartDate?: string | undefined;
    contractType?: "permanent" | "contract" | "temporary" | undefined;
    seamanBookIssuingAuthority?: string | undefined;
}>;
export type CreateCrewMember = z.infer<typeof CreateCrewMemberSchema>;
export declare const CrewMemberSchema: z.ZodObject<{
    role: z.ZodEnum<["MASTER", "CHIEF_OFFICER", "SECOND_OFFICER", "THIRD_OFFICER", "DECK_OFFICER", "CHIEF_ENGINEER", "SECOND_ENGINEER", "THIRD_ENGINEER", "ENGINE_OFFICER", "ELECTRO_TECHNICAL_OFFICER", "ABLE_SEAMAN", "ORDINARY_SEAMAN", "RATING", "CADET", "CHIEF_STEWARD", "STEWARD", "COOK", "CHIEF_COOK", "PURSER", "SAFETY_OFFICER", "SHIP_SECURITY_OFFICER", "SECURITY_OFFICER", "RADIO_OPERATOR", "CROWD_CONTROL", "OTHER"]>;
    vesselId: z.ZodNullable<z.ZodString>;
    vesselName: z.ZodNullable<z.ZodString>;
    medicalCertificate: z.ZodNullable<z.ZodObject<{
        type: z.ZodEnum<["ENG_1", "PEME", "ILO_MLC", "OTHER"]>;
        issuingAuthority: z.ZodString;
        issueDate: z.ZodString;
        expiryDate: z.ZodString;
        documentUrl: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    }, {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    }>>;
    complianceStatus: z.ZodEnum<["compliant", "expiring", "expired", "incomplete"]>;
    expiringCertificationsCount: z.ZodNumber;
    status: z.ZodEnum<["active", "inactive", "on_leave"]>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
    familyName: z.ZodString;
    givenNames: z.ZodString;
    dateOfBirth: z.ZodString;
    placeOfBirth: z.ZodOptional<z.ZodString>;
    nationality: z.ZodString;
    gender: z.ZodEnum<["M", "F", "X"]>;
    photographUrl: z.ZodOptional<z.ZodString>;
    passportNumber: z.ZodString;
    passportIssuingCountry: z.ZodString;
    passportExpiryDate: z.ZodString;
    seamanBookNumber: z.ZodOptional<z.ZodString>;
    seamanBookIssuingAuthority: z.ZodOptional<z.ZodString>;
    id: z.ZodString;
}, "strip", z.ZodTypeAny, {
    medicalCertificate: {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    } | null;
    familyName: string;
    id: string;
    role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
    createdAt: string;
    updatedAt: string;
    passportNumber: string;
    dateOfBirth: string;
    status: "active" | "inactive" | "on_leave";
    givenNames: string;
    nationality: string;
    gender: "M" | "F" | "X";
    vesselId: string | null;
    passportIssuingCountry: string;
    passportExpiryDate: string;
    vesselName: string | null;
    complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
    expiringCertificationsCount: number;
    placeOfBirth?: string | undefined;
    photographUrl?: string | undefined;
    seamanBookNumber?: string | undefined;
    seamanBookIssuingAuthority?: string | undefined;
}, {
    medicalCertificate: {
        type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
        issuingAuthority: string;
        issueDate: string;
        expiryDate: string;
        documentUrl?: string | undefined;
    } | null;
    familyName: string;
    id: string;
    role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
    createdAt: string;
    updatedAt: string;
    passportNumber: string;
    dateOfBirth: string;
    status: "active" | "inactive" | "on_leave";
    givenNames: string;
    nationality: string;
    gender: "M" | "F" | "X";
    vesselId: string | null;
    passportIssuingCountry: string;
    passportExpiryDate: string;
    vesselName: string | null;
    complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
    expiringCertificationsCount: number;
    placeOfBirth?: string | undefined;
    photographUrl?: string | undefined;
    seamanBookNumber?: string | undefined;
    seamanBookIssuingAuthority?: string | undefined;
}>;
export type CrewMember = z.infer<typeof CrewMemberSchema>;
export declare const CrewRosterSchema: z.ZodObject<{
    vesselId: z.ZodString;
    vesselName: z.ZodString;
    crew: z.ZodArray<z.ZodObject<{
        role: z.ZodEnum<["MASTER", "CHIEF_OFFICER", "SECOND_OFFICER", "THIRD_OFFICER", "DECK_OFFICER", "CHIEF_ENGINEER", "SECOND_ENGINEER", "THIRD_ENGINEER", "ENGINE_OFFICER", "ELECTRO_TECHNICAL_OFFICER", "ABLE_SEAMAN", "ORDINARY_SEAMAN", "RATING", "CADET", "CHIEF_STEWARD", "STEWARD", "COOK", "CHIEF_COOK", "PURSER", "SAFETY_OFFICER", "SHIP_SECURITY_OFFICER", "SECURITY_OFFICER", "RADIO_OPERATOR", "CROWD_CONTROL", "OTHER"]>;
        vesselId: z.ZodNullable<z.ZodString>;
        vesselName: z.ZodNullable<z.ZodString>;
        medicalCertificate: z.ZodNullable<z.ZodObject<{
            type: z.ZodEnum<["ENG_1", "PEME", "ILO_MLC", "OTHER"]>;
            issuingAuthority: z.ZodString;
            issueDate: z.ZodString;
            expiryDate: z.ZodString;
            documentUrl: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        }, {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        }>>;
        complianceStatus: z.ZodEnum<["compliant", "expiring", "expired", "incomplete"]>;
        expiringCertificationsCount: z.ZodNumber;
        status: z.ZodEnum<["active", "inactive", "on_leave"]>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        familyName: z.ZodString;
        givenNames: z.ZodString;
        dateOfBirth: z.ZodString;
        placeOfBirth: z.ZodOptional<z.ZodString>;
        nationality: z.ZodString;
        gender: z.ZodEnum<["M", "F", "X"]>;
        photographUrl: z.ZodOptional<z.ZodString>;
        passportNumber: z.ZodString;
        passportIssuingCountry: z.ZodString;
        passportExpiryDate: z.ZodString;
        seamanBookNumber: z.ZodOptional<z.ZodString>;
        seamanBookIssuingAuthority: z.ZodOptional<z.ZodString>;
        id: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        medicalCertificate: {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        } | null;
        familyName: string;
        id: string;
        role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
        createdAt: string;
        updatedAt: string;
        passportNumber: string;
        dateOfBirth: string;
        status: "active" | "inactive" | "on_leave";
        givenNames: string;
        nationality: string;
        gender: "M" | "F" | "X";
        vesselId: string | null;
        passportIssuingCountry: string;
        passportExpiryDate: string;
        vesselName: string | null;
        complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
        expiringCertificationsCount: number;
        placeOfBirth?: string | undefined;
        photographUrl?: string | undefined;
        seamanBookNumber?: string | undefined;
        seamanBookIssuingAuthority?: string | undefined;
    }, {
        medicalCertificate: {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        } | null;
        familyName: string;
        id: string;
        role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
        createdAt: string;
        updatedAt: string;
        passportNumber: string;
        dateOfBirth: string;
        status: "active" | "inactive" | "on_leave";
        givenNames: string;
        nationality: string;
        gender: "M" | "F" | "X";
        vesselId: string | null;
        passportIssuingCountry: string;
        passportExpiryDate: string;
        vesselName: string | null;
        complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
        expiringCertificationsCount: number;
        placeOfBirth?: string | undefined;
        photographUrl?: string | undefined;
        seamanBookNumber?: string | undefined;
        seamanBookIssuingAuthority?: string | undefined;
    }>, "many">;
    safeManningRequired: z.ZodRecord<z.ZodString, z.ZodNumber>;
    safeManningActual: z.ZodRecord<z.ZodString, z.ZodNumber>;
    compliant: z.ZodBoolean;
    discrepancies: z.ZodArray<z.ZodObject<{
        role: z.ZodString;
        required: z.ZodNumber;
        actual: z.ZodNumber;
        message: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        role: string;
        required: number;
        message: string;
        actual: number;
    }, {
        role: string;
        required: number;
        message: string;
        actual: number;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    crew: {
        medicalCertificate: {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        } | null;
        familyName: string;
        id: string;
        role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
        createdAt: string;
        updatedAt: string;
        passportNumber: string;
        dateOfBirth: string;
        status: "active" | "inactive" | "on_leave";
        givenNames: string;
        nationality: string;
        gender: "M" | "F" | "X";
        vesselId: string | null;
        passportIssuingCountry: string;
        passportExpiryDate: string;
        vesselName: string | null;
        complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
        expiringCertificationsCount: number;
        placeOfBirth?: string | undefined;
        photographUrl?: string | undefined;
        seamanBookNumber?: string | undefined;
        seamanBookIssuingAuthority?: string | undefined;
    }[];
    vesselId: string;
    vesselName: string;
    compliant: boolean;
    safeManningRequired: Record<string, number>;
    safeManningActual: Record<string, number>;
    discrepancies: {
        role: string;
        required: number;
        message: string;
        actual: number;
    }[];
}, {
    crew: {
        medicalCertificate: {
            type: "OTHER" | "ENG_1" | "PEME" | "ILO_MLC";
            issuingAuthority: string;
            issueDate: string;
            expiryDate: string;
            documentUrl?: string | undefined;
        } | null;
        familyName: string;
        id: string;
        role: "OTHER" | "MASTER" | "CHIEF_OFFICER" | "SECOND_OFFICER" | "THIRD_OFFICER" | "DECK_OFFICER" | "CHIEF_ENGINEER" | "SECOND_ENGINEER" | "THIRD_ENGINEER" | "ENGINE_OFFICER" | "ELECTRO_TECHNICAL_OFFICER" | "ABLE_SEAMAN" | "ORDINARY_SEAMAN" | "RATING" | "CADET" | "CHIEF_STEWARD" | "STEWARD" | "COOK" | "CHIEF_COOK" | "PURSER" | "SAFETY_OFFICER" | "SHIP_SECURITY_OFFICER" | "SECURITY_OFFICER" | "RADIO_OPERATOR" | "CROWD_CONTROL";
        createdAt: string;
        updatedAt: string;
        passportNumber: string;
        dateOfBirth: string;
        status: "active" | "inactive" | "on_leave";
        givenNames: string;
        nationality: string;
        gender: "M" | "F" | "X";
        vesselId: string | null;
        passportIssuingCountry: string;
        passportExpiryDate: string;
        vesselName: string | null;
        complianceStatus: "compliant" | "expiring" | "expired" | "incomplete";
        expiringCertificationsCount: number;
        placeOfBirth?: string | undefined;
        photographUrl?: string | undefined;
        seamanBookNumber?: string | undefined;
        seamanBookIssuingAuthority?: string | undefined;
    }[];
    vesselId: string;
    vesselName: string;
    compliant: boolean;
    safeManningRequired: Record<string, number>;
    safeManningActual: Record<string, number>;
    discrepancies: {
        role: string;
        required: number;
        message: string;
        actual: number;
    }[];
}>;
export type CrewRoster = z.infer<typeof CrewRosterSchema>;
export declare const validateCrewMember: (crew: CrewMember, sailingDate: Date) => string[];
