"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeManningRequirementSchema = exports.VesselDocumentSchema = exports.VesselSchema = exports.CreateVesselSchema = exports.OwnerInfoSchema = exports.VesselDocumentTypeEnum = exports.VesselTypeEnum = void 0;
const zod_1 = require("zod");
exports.VesselTypeEnum = zod_1.z.enum([
    'PASSENGER_FERRY',
    'RO_RO_PASSENGER',
    'HIGH_SPEED_CRAFT',
    'CARGO',
    'TANKER',
    'OTHER',
]);
exports.VesselDocumentTypeEnum = zod_1.z.enum([
    'CERTIFICATE_OF_REGISTRY',
    'DECLARATION_OF_OWNERSHIP',
    'MANAGING_OWNER_REGISTRATION',
    'AUTHORIZED_OFFICER_APPOINTMENT',
    'SAFETY_MANAGEMENT_CERTIFICATE',
    'DOCUMENT_OF_COMPLIANCE',
    'PASSENGER_SHIP_SAFETY_CERTIFICATE',
    'MINIMUM_SAFE_MANNING_DOCUMENT',
    'INTERNATIONAL_TONNAGE_CERTIFICATE',
    'LOAD_LINE_CERTIFICATE',
    'P_AND_I_INSURANCE',
    'HULL_INSURANCE',
    'WET_LEASE_AGREEMENT',
    'DRY_LEASE_AGREEMENT',
    'BAREBOAT_CHARTER',
    'CLASS_CERTIFICATE',
    'OTHER',
]);
exports.OwnerInfoSchema = zod_1.z.object({
    name: zod_1.z.string().min(1).max(200),
    type: zod_1.z.enum(['individual', 'company']),
    address: zod_1.z.object({
        street: zod_1.z.string(),
        city: zod_1.z.string(),
        state: zod_1.z.string().optional(),
        postalCode: zod_1.z.string().optional(),
        country: zod_1.z.string().length(3),
    }),
    contactEmail: zod_1.z.string().email(),
    contactPhone: zod_1.z.string(),
    registrationNumber: zod_1.z.string().optional(),
});
exports.CreateVesselSchema = zod_1.z.object({
    name: zod_1.z.string().min(1).max(100),
    imoNumber: zod_1.z.string().regex(/^IMO\d{7}$/),
    officialNumber: zod_1.z.string().max(50).optional(),
    callSign: zod_1.z.string().max(20).optional(),
    mmsi: zod_1.z.string().length(9).optional(),
    flagState: zod_1.z.string().length(3).default('BHS'),
    portOfRegistry: zod_1.z.string().default('Nassau'),
    type: exports.VesselTypeEnum,
    classificationSociety: zod_1.z.string().optional(),
    classNotation: zod_1.z.string().optional(),
    grossTonnage: zod_1.z.number().positive(),
    netTonnage: zod_1.z.number().positive(),
    lengthOverall: zod_1.z.number().positive(),
    breadth: zod_1.z.number().positive().optional(),
    depth: zod_1.z.number().positive().optional(),
    passengerCapacity: zod_1.z.number().nonnegative().optional(),
    crewCapacity: zod_1.z.number().nonnegative().optional(),
    vehicleCapacity: zod_1.z.number().nonnegative().optional(),
    engineType: zod_1.z.string().optional(),
    engineCount: zod_1.z.number().optional(),
    propulsionPower: zod_1.z.number().optional(),
    registeredOwner: exports.OwnerInfoSchema,
    managingOwner: exports.OwnerInfoSchema.optional(),
    yearBuilt: zod_1.z.number().min(1900).max(new Date().getFullYear()),
    builder: zod_1.z.string().optional(),
    buildCountry: zod_1.z.string().length(3).optional(),
});
exports.VesselSchema = zod_1.z.object({
    id: zod_1.z.string().uuid(),
    ...exports.CreateVesselSchema.shape,
    status: zod_1.z.enum(['active', 'inactive', 'laid_up', 'sold']),
    complianceStatus: zod_1.z.object({
        safeManningCompliant: zod_1.z.boolean(),
        documentsValid: zod_1.z.boolean(),
        insuranceValid: zod_1.z.boolean(),
        certificatesValid: zod_1.z.boolean(),
    }),
    documentCount: zod_1.z.number(),
    expiringDocumentsCount: zod_1.z.number(),
    createdAt: zod_1.z.string(),
    updatedAt: zod_1.z.string(),
});
exports.VesselDocumentSchema = zod_1.z.object({
    id: zod_1.z.string().uuid(),
    vesselId: zod_1.z.string().uuid(),
    type: exports.VesselDocumentTypeEnum,
    typeName: zod_1.z.string(),
    title: zod_1.z.string(),
    description: zod_1.z.string().optional(),
    fileName: zod_1.z.string(),
    fileSize: zod_1.z.number(),
    mimeType: zod_1.z.string(),
    documentUrl: zod_1.z.string(),
    issueDate: zod_1.z.string().optional(),
    expiryDate: zod_1.z.string().optional(),
    daysUntilExpiry: zod_1.z.number().nullable(),
    status: zod_1.z.enum(['valid', 'expiring', 'expired', 'pending_review']),
    verified: zod_1.z.boolean(),
    uploadedAt: zod_1.z.string(),
    uploadedBy: zod_1.z.string().uuid(),
    verifiedAt: zod_1.z.string().nullable(),
    verifiedBy: zod_1.z.string().uuid().nullable(),
});
exports.SafeManningRequirementSchema = zod_1.z.object({
    vesselId: zod_1.z.string().uuid(),
    documentNumber: zod_1.z.string(),
    issueDate: zod_1.z.string(),
    expiryDate: zod_1.z.string().optional(),
    issuingAuthority: zod_1.z.string().default('Bahamas Maritime Authority'),
    requirements: zod_1.z.array(zod_1.z.object({
        role: zod_1.z.string(),
        minimumCount: zod_1.z.number(),
        certificateRequired: zod_1.z.string(),
        notes: zod_1.z.string().optional(),
    })),
});
//# sourceMappingURL=vessel.js.map