import { z } from 'zod';
export declare const UpsertVesselMSMDSchema: z.ZodObject<{
    msmdReferenceNumber: z.ZodString;
    issueDate: z.ZodString;
    expiryDate: z.ZodString;
    masterRequired: z.ZodNumber;
    chiefOfficerRequired: z.ZodNumber;
    deckOfficerRequired: z.ZodNumber;
    chiefEngineerRequired: z.ZodNumber;
    engineerOfficerRequired: z.ZodNumber;
    ratingsDeckRequired: z.ZodNumber;
    ratingsEngineRequired: z.ZodNumber;
    securityOfficerRequired: z.ZodNumber;
    radioOperatorRequired: z.ZodNumber;
    cookRequired: z.ZodNumber;
    crowdControlRequired: z.ZodNumber;
    maxPassengersForManning: z.ZodOptional<z.ZodNumber>;
    operationalArea: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    issueDate: string;
    expiryDate: string;
    msmdReferenceNumber: string;
    masterRequired: number;
    chiefOfficerRequired: number;
    deckOfficerRequired: number;
    chiefEngineerRequired: number;
    engineerOfficerRequired: number;
    ratingsDeckRequired: number;
    ratingsEngineRequired: number;
    securityOfficerRequired: number;
    radioOperatorRequired: number;
    cookRequired: number;
    crowdControlRequired: number;
    maxPassengersForManning?: number | undefined;
    operationalArea?: string | undefined;
}, {
    issueDate: string;
    expiryDate: string;
    msmdReferenceNumber: string;
    masterRequired: number;
    chiefOfficerRequired: number;
    deckOfficerRequired: number;
    chiefEngineerRequired: number;
    engineerOfficerRequired: number;
    ratingsDeckRequired: number;
    ratingsEngineRequired: number;
    securityOfficerRequired: number;
    radioOperatorRequired: number;
    cookRequired: number;
    crowdControlRequired: number;
    maxPassengersForManning?: number | undefined;
    operationalArea?: string | undefined;
}>;
export type UpsertVesselMSMD = z.infer<typeof UpsertVesselMSMDSchema>;
